### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by dsmora** [4GeeksAcademy/AdrianAlarcon-GeneradorDeNombres#1]
- [x] Has creado un archivo en la raíz llamado app.js, el ejercicio había que trabajarlo en src/app.js, copia y pega el código y borra ese archivo de fuera, porque si no no se ejecuta al levantar el proyecto. 
- [x] He revisado tu archivo app.js donde tienes el código, esta todo bien, pero estas añadiendo los elementos generados a un array, y imprimiendo el array en la consola, tenemos que imprimir cada dominio generado.

**Comment by COCOASOO** [comment]
hecho
